### ISSUE TITLE
Add support for Set model type

### ISSUE THREAD

**Issue by adamlwgriffiths** [sopherapps/pydantic-redis#1]
Just came across your project and its _exactly_ how I was going to write this myself, but you've integrated it with pydantic which looks interesting.

Do you have plans to support Redis sets?

At first glance it would be a model with two fields: a primary key, and the actual data type itself.

**Comment by Tinitto** [comment]
@adamlwgriffiths , I was just apologizing to someone else that I keep missing notifications about activities on these repos and since there is usually very minimal activity, I don't notice till years later.

To answer your question, I worked on this on a certain weekend as a hobby. I never got to really use it on a production project. I guess if you or anyone else is interested in advancing it, just let me know because I don't see myself adding more stuff to it.

**Comment by adamlwgriffiths** [comment]
No problems. I ended up writing some of my own code but also walked away from that too =P
Such is the nature of things.
